<?xml version="1.0" encoding="utf-8"?><Database Name="adminPC" Class="DataDiagramDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-8T21MBV\SQLEXPRESS;Initial Catalog=adminPC;Integrated Security=True" SettingsObjectName="DAL.Properties.Settings" SettingsPropertyName="adminPCConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.DuAn" Member="DuAns">
    <Type Name="DuAn">
      <Column Name="MaDA" Type="System.String" DbType="NChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenDA" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="DiaDiem" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="MaPB" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Association Name="DuAn_PhanCong" Member="PhanCongs" ThisKey="MaDA" OtherKey="MaDA" Type="PhanCong" />
      <Association Name="PhongBan_DuAn" Member="PhongBan" ThisKey="MaPB" OtherKey="MaPB" Type="PhongBan" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.NhanVien" Member="NhanViens">
    <Type Name="NhanVien">
      <Column Name="MaNV" Type="System.String" DbType="NChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="HoTen" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="NS" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="GT" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Luong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaNGS" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="MaPB" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Association Name="NhanVien_PhanCong" Member="PhanCongs" ThisKey="MaNV" OtherKey="MaNV" Type="PhanCong" />
      <Association Name="PhongBan_NhanVien" Member="PhongBan" ThisKey="MaPB" OtherKey="MaPB" Type="PhongBan" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PhanCong" Member="PhanCongs">
    <Type Name="PhanCong">
      <Column Name="MaNV" Type="System.String" DbType="NChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaDA" Type="System.String" DbType="NChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SoGio" Type="System.Decimal" DbType="Decimal(3,1)" CanBeNull="true" />
      <Association Name="DuAn_PhanCong" Member="DuAn" ThisKey="MaDA" OtherKey="MaDA" Type="DuAn" IsForeignKey="true" />
      <Association Name="NhanVien_PhanCong" Member="NhanVien" ThisKey="MaNV" OtherKey="MaNV" Type="NhanVien" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PhongBan" Member="PhongBans">
    <Type Name="PhongBan">
      <Column Name="MaPB" Type="System.String" DbType="NChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenPB" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="DiaDiem" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="MaTP" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Association Name="PhongBan_DuAn" Member="DuAns" ThisKey="MaPB" OtherKey="MaPB" Type="DuAn" />
      <Association Name="PhongBan_NhanVien" Member="NhanViens" ThisKey="MaPB" OtherKey="MaPB" Type="NhanVien" />
    </Type>
  </Table>
  <Table Name="dbo.TaiKhoan" Member="TaiKhoans">
    <Type Name="TaiKhoan">
      <Column Name="username" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="password" Type="System.String" DbType="NChar(20)" CanBeNull="true" />
      <Column Name="name" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="phone" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="email" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
</Database>